### ISSUE TITLE
Error while updating iot-uni-dongle for ESPHome 2022.9.0

### ISSUE THREAD

**Issue by enkorsh** [dentra/esphome-ewh#3]
Hello!
Updated ESPHome to version 2022.9.0
Errors occur when updating iot-uni-dongle:

INFO Reading configuration /config/esphome/water-heat.yaml...
ERROR Unable to load component ewh:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/5e7bb4e7/components/ewh/__init__.py", line 65, in <module>
    cv.Optional(CONF_ICON, default=ICON_WATER_BOILER): switch.icon,
AttributeError: module 'esphome.components.switch' has no attribute 'icon'
ERROR Unable to load component ewh.climate:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/5e7bb4e7/components/ewh/__init__.py", line 65, in <module>
    cv.Optional(CONF_ICON, default=ICON_WATER_BOILER): switch.icon,
AttributeError: module 'esphome.components.switch' has no attribute 'icon'
INFO Detected timezone 'Europe/Moscow'
Failed config

ewh: [source /config/esphome/.esphome/packages/3a7dff6c/ewh-pkg-web.yaml:128]
  
  Component not found: ewh.
  on_state: 
    then: 
      - lambda: |-
          id(wh_current_temp).publish_state(state.current_temperature);
          id(wh_target_temp).publish_state(state.target_temperature);
          switch(state.state) {
            case ewh::ewh_status_t::STATE_700W:
              id(wh_state).publish_state(true);
              id(wh_mode).publish_state("700 W");
              break;
            case ewh::ewh_status_t::STATE_1300W:
              id(wh_state).publish_state(true);
              id(wh_mode).publish_state("1300 W");
              break;
            case ewh::ewh_status_t::STATE_2000W:
              id(wh_state).publish_state(true);
              id(wh_mode).publish_state("2000 W");
              break;
            case ewh::ewh_status_t::STATE_TIMER:
              id(wh_state).publish_state(true);
              id(wh_mode).publish_state("Timer");
              break;
            case ewh::ewh_status_t::STATE_NO_FROST:
              id(wh_state).publish_state(true);
              id(wh_mode).publish_state("No Frost");
              break;
            default:
              id(wh_state).publish_state(false);
              break;
          }
  id: wh
climate.ewh: [source /config/esphome/.esphome/packages/3a7dff6c/ewh-pkg-ewh.yaml:38]
  
  Platform not found: 'climate.ewh'.
  platform: ewh
  id: whc
  name: Water Heater
  bst: 
    name: Water Heater BST

Help me please

**Comment by dentra** [comment]
this is due breaking changes in esphome api, will fix.

**Comment by enkorsh** [comment]
thank you very much, best regards, Eugene

**Comment by dentra** [comment]
now updated

**Comment by enkorsh** [comment]
Hello, I tried to update, while compiling an error occurs.
![Error_update](https://user-images.githubusercontent.com/56437218/199027777-27984dc9-a4f3-43eb-8129-1105dd527a1f.png)

**Comment by dentra** [comment]
Please uncomment clock or timer as workaround

**Comment by enkorsh** [comment]
Thanks, all worked well
